version: '3'
services: 
  tsc: 
    build:
      context: .
      dockerfile: 'containers/node/Dockerfile'
    command: 'tsc -w'
    volumes: 
      - './api:/api'
  node: 
    command: 'nodemon /api/dist/main.js'
    ports: 
      - '3000:3000'    
    depends_on: 
      - 'tsc'
  vue: 
    command: 'npm run dev'
    ports: 
      - 8080:8080
    environment: 
      - API_HOST=http://localhost:3000