version: '3'
volumes: 
  mongo-data:
services: 
  mongodb: 
    image: mongo:latest
    environment: 
      - MONGO_DATA_DIR=/data/db
    volumes: 
      - 'mongo-data:/data/db'
    ports: 
      - '27017:27017'
    command: mongod
  node: 
    build:
      context: .
      dockerfile: 'containers/node/Dockerfile'
    volumes: 
      - './api:/api'
    ports: 
      - '3000:3000'
    depends_on:
      - mongodb