version: '3'
services: 
  node: 
    command: 'pm2 start /api/dist/main.js -i 0'
    ports: 
      - '4000:4000'    
    depends_on: 
      - 'mongodb'
  vue: 
    command: 'npm run build'
    ports: 
      - 8080:8080
    environment:       
      - API_HOST=http://api-dito.thiagoabreudev.com.br
  nginx:
    image: nginx:1.13
    volumes:      
      - ./containers/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/html
    ports: 
      - 80:80        