version: '3'
volumes: 
  mongo-data:
services: 
  mongodb: 
    image: mongo:latest
    environment: 
      - MONGO_DATA_DIR=/data/db
    volumes: 
      - 'mongo-data:/data/db'
    ports: 
      - '27017:27017'
    command: mongod
  node: 
    build:
      context: .
      dockerfile: 'containers/node/Dockerfile'
    volumes: 
      - './api:/api'
    depends_on:
      - mongodb
  vue:
    build:
      context: .
      dockerfile: 'containers/vue/Dockerfile'
    volumes:
      - './frontend:/frontend'
    depends_on:
      - node
    environment:
      - HOST=0.0.0.0
      - PORT=8080